"""empty message

Revision ID: 2c7a2d3f8cb2
Revises: f6acaf5c208c
Create Date: 2021-09-15 14:17:56.137659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7a2d3f8cb2'
down_revision = 'f6acaf5c208c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
